### ISSUE TITLE
How to get response details?

### ISSUE THREAD

**Issue by Matt2012** [ianbibby/facebook-auth#1]
Sorry must be missing something obvious but how do I get avatar / name etc.? Not seeing this on the console.log("Logged in", e);

**Comment by ianbibby** [comment]
Hi Matt,

Once you're logged in, you should be able to perform the following:

``` javascript
window.FB.api('me', function(e) { console.log(e); })
```

If you'd like the avatar, you can use this URL to get a 302 redirect to the real image location:

http://graph.facebook.com/facebook-id-here/picture

Hope that helps!
